#ifndef DREAMPLACE_NAMESPACE_H
#define DREAMPLACE_NAMESPACE_H

#define DREAMPLACE_NAMESPACE DreamPlace
#define DREAMPLACE_BEGIN_NAMESPACE namespace DreamPlace {
#define DREAMPLACE_END_NAMESPACE }

#endif




